[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "date_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "Date", DestinationColumnName = "Date"], [SourceColumnName = "DateNum", DestinationColumnName = "DateNum"], [SourceColumnName = "YearMonthNum", DestinationColumnName = "YearMonthNum"], [SourceColumnName = "Calendar_Quarter", DestinationColumnName = "Calendar_Quarter"], [SourceColumnName = "MonthNum", DestinationColumnName = "MonthNum"], [SourceColumnName = "MonthName", DestinationColumnName = "MonthName"], [SourceColumnName = "MonthShortName", DestinationColumnName = "MonthShortName"], [SourceColumnName = "WeekNum", DestinationColumnName = "WeekNum"], [SourceColumnName = "DayNumOfYear", DestinationColumnName = "DayNumOfYear"], [SourceColumnName = "DayNumOfMonth", DestinationColumnName = "DayNumOfMonth"], [SourceColumnName = "DayNumOfWeek", DestinationColumnName = "DayNumOfWeek"], [SourceColumnName = "DayName", DestinationColumnName = "DayName"], [SourceColumnName = "DayShortName", DestinationColumnName = "DayShortName"], [SourceColumnName = "Quarter", DestinationColumnName = "Quarter"], [SourceColumnName = "YearQuarterNum", DestinationColumnName = "YearQuarterNum"], [SourceColumnName = "DayNumOfQuarter", DestinationColumnName = "DayNumOfQuarter"], [SourceColumnName = "NorthernHemispherSeason", DestinationColumnName = "NorthernHemispherSeason"], [SourceColumnName = "SouthernHemispherSeason", DestinationColumnName = "SouthernHemispherSeason"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared date = let
  Source = Csv.Document(Web.Contents("https://6x2gqg-my.sharepoint.com/personal/sahar_6x2gqg_onmicrosoft_com/Documents/Apps/Microsoft Power Query/Uploaded Files/date.csv"), [Delimiter = ",", Columns = 18, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"DateNum", Int64.Type}, {"Date", type date}, {"YearMonthNum", Int64.Type}, {"Calendar_Quarter", type text}, {"MonthNum", Int64.Type}, {"MonthName", type text}, {"MonthShortName", type text}, {"WeekNum", Int64.Type}, {"DayNumOfYear", Int64.Type}, {"DayNumOfMonth", Int64.Type}, {"DayNumOfWeek", Int64.Type}, {"DayName", type text}, {"DayShortName", type text}, {"Quarter", Int64.Type}, {"YearQuarterNum", Int64.Type}, {"DayNumOfQuarter", Int64.Type}, {"NorthernHemispherSeason", type text}, {"SouthernHemispherSeason", type text}}),
  #"Reordered columns" = Table.ReorderColumns(#"Changed column type", {"Date", "DateNum", "YearMonthNum", "Calendar_Quarter", "MonthNum", "MonthName", "MonthShortName", "WeekNum", "DayNumOfYear", "DayNumOfMonth", "DayNumOfWeek", "DayName", "DayShortName", "Quarter", "YearQuarterNum", "DayNumOfQuarter", "NorthernHemispherSeason", "SouthernHemispherSeason"})
in
  #"Reordered columns";
shared date_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false, HierarchicalNavigation = null]),
  Navigation_1 = Pattern{[workspaceId = "bb1444cd-93a8-4c08-a21a-87ee9a1ca8ad"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "ff092a76-b4ad-4ff9-80c6-4c30ba503591"]}[Data],
  TableNavigation = Navigation_2{[Item = "dim_date", Schema = "dbo"]}?[Data]?
in
  TableNavigation;
